app/urls.py
from django.conf.urls import url
from django.urls import path, include

from .views import *

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("", home, name="home"),

    path("register", register, name="register"),
    path("register-owner", add_owner, name="add-owner"),
    path("register-user", add_client, name="add-client"),
    path("register-restaurant", add_restaurant, name="add-restaurant"),
    path("client/", client_profile, name="client"),
    url("client/(?P<name>.+)", client_profile, name="client"),
    path("owner/", owner_profile, name="owner"),
    url("owner/(?P<name>.+)", owner_profile, name="owner"),
    path("my-restaurants", owner_restaurants, name="my-restaurants"),
    path("edit-restaurant/<int:number>", edit_restaurant, name="edit-restaurant"),
    path("restaurant/<int:number>", restaurant_detail, name="restaurant-detail"),
    path("list-restaurants", restaurant_listing, name="restaurant-listing"),
    path("my-favorites", favorites_listing, name="favourites_listing"),
    path("reload-database", reload_database, name="reload_database"),
]

tpw_project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
]

app/forms.py
from django import forms


class AddPerson(forms.Form):
    email = forms.EmailField(label="Email", help_text="Insert Email")
    first_name = forms.CharField(label="First Name", help_text="Insert First Name")
    last_name = forms.CharField(label="Last Name", help_text="Insert Last Name")
    phone_number = forms.CharField(label="Phone Number", help_text="Insert Phone Number")
    photo = forms.ImageField(label="Photo", required=False)
    password = forms.CharField(label="Password", required=False, help_text="Password",
                               widget=forms.PasswordInput())
    repeat_password = forms.CharField(label="Repeat Password", required=False, help_text="Repeat Password",
                                      widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "photo":
                field.widget.attrs["placeholder"] = field.help_text
                field.widget.attrs["class"] = "input100"


class AddRestaurant(forms.Form):
    name = forms.CharField(label="Name", help_text="Insert Name")
    address = forms.CharField(label="Address", help_text="Insert Address")
    city = forms.CharField(label="City", help_text="Insert City")
    zip_code = forms.CharField(label="Zip Code", help_text="Insert Zip Code")
    phone_number = forms.CharField(label="Phone Number", help_text="Insert Phone Number")

    country_choices = (
        ("Afghanistan", "Afghanistan"), ("Albania", "Albania"), ("Algeria", "Algeria"), ("Andorra", "Andorra"),
        ("Angola", "Angola"), ("Antigua & Deps", "Antigua & Deps"), ("Argentina", "Argentina"),
        ("Armenia", "Armenia"), ("Australia", "Australia"), ("Austria", "Austria"), ("Azerbaijan", "Azerbaijan"),
        ("Bahamas", "Bahamas"), ("Bahrain", "Bahrain"), ("Bangladesh", "Bangladesh"), ("Barbados", "Barbados"),
        ("Belarus", "Belarus"), ("Belgium", "Belgium"), ("Belize", "Belize"), ("Benin", "Benin"), ("Bhutan", "Bhutan"),
        ("Bolivia", "Bolivia"), ("Bosnia Herzegovina", "Bosnia Herzegovina"), ("Botswana", "Botswana"),
        ("Brazil", "Brazil"), ("Brunei", "Brunei"), ("Bulgaria", "Bulgaria"), ("Burkina", "Burkina"),
        ("Burundi", "Burundi"), ("Cambodia", "Cambodia"), ("Cameroon", "Cameroon"), ("Canada", "Canada"),
        ("Cape Verde", "Cape Verde"), ("Central African Rep", "Central African Rep"), ("Chad", "Chad"),
        ("Chile", "Chile"), ("China", "China"), ("Colombia", "Colombia"), ("Comoros", "Comoros"), ("Congo", "Congo"),
        ("Congo Democratic Rep", "Congo Democratic Rep"), ("Costa Rica", "Costa Rica"), ("Croatia", "Croatia"),
        ("Cuba", "Cuba"), ("Cyprus", "Cyprus"), ("Czech Republic", "Czech Republic"), ("Denmark", "Denmark"),
        ("Djibouti", "Djibouti"), ("Dominica", "Dominica"), ("Dominican Republic", "Dominican Republic"),
        ("East Timor", "East Timor"), ("Ecuador", "Ecuador"), ("Egypt", "Egypt"), ("El Salvador", "El Salvador"),
        ("Equatorial Guinea", "Equatorial Guinea"), ("Eritrea", "Eritrea"), ("Estonia", "Estonia"),
        ("Ethiopia", "Ethiopia"), ("Fiji", "Fiji"), ("Finland", "Finland"), ("France", "France"), ("Gabon", "Gabon"),
        ("Gambia", "Gambia"), ("Georgia", "Georgia"), ("Germany", "Germany"), ("Ghana", "Ghana"), ("Greece", "Greece"),
        ("Grenada", "Grenada"), ("Guatemala", "Guatemala"), ("Guinea", "Guinea"), ("Guinea-Bissau", "Guinea-Bissau"),
        ("Guyana", "Guyana"), ("Haiti", "Haiti"), ("Honduras", "Honduras"), ("Hungary", "Hungary"),
        ("Iceland", "Iceland"), ("India", "India"), ("Indonesia", "Indonesia"), ("Iran", "Iran"), ("Iraq", "Iraq"),
        ("Ireland Republic", "Ireland Republic"), ("Israel", "Israel"), ("Italy", "Italy"),
        ("Ivory Coast", "Ivory Coast"), ("Jamaica", "Jamaica"), ("Japan", "Japan"), ("Jordan", "Jordan"),
        ("Kazakhstan", "Kazakhstan"), ("Kenya", "Kenya"), ("Kiribati", "Kiribati"), ("Korea North", "Korea North"),
        ("Korea South", "Korea South"), ("Kosovo", "Kosovo"), ("Kuwait", "Kuwait"), ("Kyrgyzstan", "Kyrgyzstan"),
        ("Laos", "Laos"), ("Latvia", "Latvia"), ("Lebanon", "Lebanon"), ("Lesotho", "Lesotho"), ("Liberia", "Liberia"),
        ("Libya", "Libya"), ("Liechtenstein", "Liechtenstein"), ("Lithuania", "Lithuania"),
        ("Luxembourg", "Luxembourg"), ("Macedonia", "Macedonia"), ("Madagascar", "Madagascar"), ("Malawi", "Malawi"),
        ("Malaysia", "Malaysia"), ("Maldives", "Maldives"), ("Mali", "Mali"), ("Malta", "Malta"),
        ("Marshall Islands", "Marshall Islands"), ("Mauritania", "Mauritania"), ("Mauritius", "Mauritius"),
        ("Mexico", "Mexico"), ("Micronesia", "Micronesia"), ("Moldova", "Moldova"), ("Monaco", "Monaco"),
        ("Mongolia", "Mongolia"), ("Montenegro", "Montenegro"), ("Morocco", "Morocco"), ("Mozambique", "Mozambique"),
        ("Myanmar", "Myanmar"), ("Namibia", "Namibia"), ("Nauru", "Nauru"), ("Nepal", "Nepal"),
        ("Netherlands", "Netherlands"), ("New Zealand", "New Zealand"), ("Nicaragua", "Nicaragua"), ("Niger", "Niger"),
        ("Nigeria", "Nigeria"), ("Norway", "Norway"), ("Oman", "Oman"), ("Pakistan", "Pakistan"), ("Palau", "Palau"),
        ("Panama", "Panama"), ("Papua New Guinea", "Papua New Guinea"), ("Paraguay", "Paraguay"), ("Peru", "Peru"),
        ("Philippines", "Philippines"), ("Poland", "Poland"), ("Portugal", "Portugal"), ("Qatar", "Qatar"),
        ("Romania", "Romania"), ("Russian Federation", "Russian Federation"), ("Rwanda", "Rwanda"),
        ("St Kitts & Nevis", "St Kitts & Nevis"), ("St Lucia", "St Lucia"),
        ("Saint Vincent & the Grenadines", "Saint Vincent & the Grenadines"), ("Samoa", "Samoa"),
        ("San Marino", "San Marino"), ("Sao Tome & Principe", "Sao Tome & Principe"), ("Saudi Arabia", "Saudi Arabia"),
        ("Senegal", "Senegal"), ("Serbia", "Serbia"), ("Seychelles", "Seychelles"), ("Sierra Leone", "Sierra Leone"),
        ("Singapore", "Singapore"), ("Slovakia", "Slovakia"), ("Slovenia", "Slovenia"),
        ("Solomon Islands", "Solomon Islands"), ("Somalia", "Somalia"), ("South Africa", "South Africa"),
        ("South Sudan", "South Sudan"), ("Spain", "Spain"), ("Sri Lanka", "Sri Lanka"), ("Sudan", "Sudan"),
        ("Suriname", "Suriname"), ("Swaziland", "Swaziland"), ("Sweden", "Sweden"), ("Switzerland", "Switzerland"),
        ("Syria", "Syria"), ("Taiwan", "Taiwan"), ("Tajikistan", "Tajikistan"), ("Tanzania", "Tanzania"),
        ("Thailand", "Thailand"), ("Togo", "Togo"), ("Tonga", "Tonga"), ("Trinidad & Tobago", "Trinidad & Tobago"),
        ("Tunisia", "Tunisia"), ("Turkey", "Turkey"), ("Turkmenistan", "Turkmenistan"), ("Tuvalu", "Tuvalu"),
        ("Uganda", "Uganda"), ("Ukraine", "Ukraine"), ("United Arab Emirates", "United Arab Emirates"),
        ("United Kingdom", "United Kingdom"), ("United States", "United States"), ("Uruguay", "Uruguay"),
        ("Uzbekistan", "Uzbekistan"), ("Vanuatu", "Vanuatu"), ("Vatican City", "Vatican City"),
        ("Venezuela", "Venezuela"), ("Vietnam", "Vietnam"), ("Yemen", "Yemen"), ("Zambia", "Zambia"),
        ("Zimbabwe", "Zimbabwe"))
    country = forms.ChoiceField(label="Country", choices=country_choices)

    latitude = forms.FloatField(label="Latitude", help_text="Insert Latitude")
    longitude = forms.CharField(label="Longitude", help_text="Insert Longitude")
    photo = forms.ImageField(label="Photo", required=False)

    def __init__(self, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "photo" and field_name != "country":
                field.widget.attrs["placeholder"] = field.help_text
                field.widget.attrs["class"] = "input100"

            elif field_name == "country":
                field.widget.attrs["placeholder"] = field.help_text
                field.widget.attrs["class"] = "form-control"


class UpdateClient(forms.Form):
    email = forms.EmailField(label="Email", help_text="Insert Email")
    first_name = forms.CharField(label="First Name", help_text="Insert First Name")
    last_name = forms.CharField(label="Last Name", help_text="Insert Last Name")
    phone_number = forms.CharField(label="Phone Number", help_text="Insert Phone Number")
    photo = forms.ImageField(label="Photo", required=False)
    new_password = forms.CharField(label="New Password", required=False, help_text="New Password",
                                   widget=forms.PasswordInput())
    repeat_password = forms.CharField(label="Repeat New Password", required=False, help_text="Repeat New Password",
                                      widget=forms.PasswordInput())

    def __init__(self, user, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["placeholder"] = field.help_text
            field.widget.attrs["class"] = "input100"

        if user is not None:
            for field_name, field in self.fields.items():
                if field_name == "first_name":
                    field.initial = user.user.first_name

                if field_name == "last_name":
                    field.initial = user.user.last_name

                if field_name == "email":
                    field.initial = user.user.email

                if field_name == "phone_number":
                    field.initial = user.phone_number

                if field_name == "photo":
                    field.widget.attrs["class"] = "col-md-3 col-sm-3"
                    field.initial = "data:image/png;base64," + user.photo


class UpdateOwner(forms.Form):
    email = forms.EmailField(label="Email", help_text="Insert Email")
    first_name = forms.CharField(label="First Name", help_text="Insert First Name")
    last_name = forms.CharField(label="Last Name", help_text="Insert Last Name")

app/templates/add_client.html
{% extends 'base.html' %}

{% load static %}

{% block title %} New Client {% endblock %}

{% block content %}
    <div class="container-login100 mt-5">
        <div class="wrap-login100 wea pt-5 pb-5">

            <form id="login-form" class="login100-form validate-form flex-sb flex-w" method="post" enctype="multipart/form-data">

                <span class="login100-form-title pb-5">New User</span>

                {% if form.errors or state is not None and not state %}
                    <div class="body col-12 mb-4">
                        <ul class="errornote">
                            <li>Please, correct the errors bellow.</li>
                            <li>{{ message }}</li>
                        </ul>
                    </div>
                {% endif %}

                <div class="follow-img" style="text-align: left; max-width: 15em">
                    <img id="photo"
                         src="https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/256x256/plain/user.png"
                         class="img-fluid" alt="#">
                </div>
                <div class="mt-3 mb-5 ml-3 pl-5">
                    <btn class="btn btn-primary btn-lg" id="edit_img">Adicionar foto</btn>
                    <div style="visibility: hidden;">{{ form.photo }}</div>
                </div>

                {{ form.email.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.email }}
                    <span class="focus-input100"></span>
                    {{ form.email.errors }}
                </div>

                {{ form.password.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.password }}
                    <span class="focus-input100"></span>
                    {{ form.password.errors }}
                </div>

                {{ form.repeat_password.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.repeat_password }}
                    <span class="focus-input100"></span>
                    {{ form.repeat_password.errors }}
                </div>

                {{ form.first_name.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.first_name }}
                    <span class="focus-input100"></span>
                    {{ form.first_name.errors }}
                </div>


                {{ form.last_name.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.last_name }}
                    <span class="focus-input100"></span>
                    {{ form.last_name.errors }}
                </div>


                {{ form.phone_number.label_tag }}
                <div class="wrap-input100 mb-4">
                    {{ form.phone_number }}
                    <span class="focus-input100"></span>
                    {{ form.phone_number.errors }}
                </div>

                <div class="container-login100-form-btn mt-5">
                    <button type="submit" class="login100-form-btn">Register</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

{% block script %}
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#photo').attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#id_photo").change(function () {
            readURL(this);
        });

        $('#edit_img').click(function () {
            $("#id_photo").trigger("click");
        });
    </script>
{% endblock script %}

app/templates/add_owner.html
{% extends 'base.html' %}

{% load static %}

{% block title %} New Owner {% endblock %}

{% block content %}
    <div class="container-login100 mt-5">
        <div class="wrap-login100 wea pt-5 pb-5">

            <form id="login-form" class="login100-form validate-form flex-sb flex-w" method="post" enctype="multipart/form-data">

                <span class="login100-form-title pb-5">New Owner</span>

                {% if form.errors or state is not None and not state %}
                    <div class="body col-12 mb-4">
                        <ul class="errornote">
                            <li>Please, correct the errors bellow.</li>
                            <li>{{ message }}</li>
                        </ul>
                    </div>
                {% endif %}

                <div class="follow-img" style="text-align: left; max-width: 15em">
                    <img id="photo"
                         src="https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/256x256/plain/user.png"
                         class="img-fluid" alt="#">
                </div>
                <div class="mt-3 mb-5 ml-3 pl-5">
                    <btn class="btn btn-primary btn-lg" id="edit_img">Adicionar foto</btn>
                    <div style="visibility: hidden;">{{ form.photo }}</div>
                </div>

                {{ form.email.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.email }}
                    <span class="focus-input100"></span>
                    {{ form.email.errors }}
                </div>

                {{ form.password.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.password }}
                    <span class="focus-input100"></span>
                    {{ form.password.errors }}
                </div>

                {{ form.repeat_password.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.repeat_password }}
                    <span class="focus-input100"></span>
                    {{ form.repeat_password.errors }}
                </div>

                {{ form.first_name.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.first_name }}
                    <span class="focus-input100"></span>
                    {{ form.first_name.errors }}
                </div>


                {{ form.last_name.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.last_name }}
                    <span class="focus-input100"></span>
                    {{ form.last_name.errors }}
                </div>


                {{ form.phone_number.label_tag }}
                <div class="wrap-input100 mb-4">
                    {{ form.phone_number }}
                    <span class="focus-input100"></span>
                    {{ form.phone_number.errors }}
                </div>

                <div class="container-login100-form-btn mt-5">
                    <button type="submit" class="login100-form-btn">Register</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

{% block script %}
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#photo').attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#id_photo").change(function () {
            readURL(this);
        });

        $('#edit_img').click(function () {
            $("#id_photo").trigger("click");
        });
    </script>
{% endblock script %}

app/templates/add_restaurant.html
{% extends 'base.html' %}

{% load static %}

{% block title %} New Restaurant {% endblock %}

{% block content %}
    <div class="container-login100 mt-5">
        <div class="wrap-login100 wea pt-5 pb-5">

            <form id="login-form" class="login100-form validate-form flex-sb flex-w" method="post"
                  enctype="multipart/form-data">

                <span class="login100-form-title pb-5">New Restaurant</span>

                {% if form.errors or state is not None and not state %}
                    <div class="body col-12 mb-4">
                        <ul class="errornote">
                            <li>Please, correct the errors bellow.</li>
                            <li>{{ message }}</li>
                        </ul>
                    </div>
                {% endif %}

                <div class="follow-img">
                    <img id="photo"
                         src="https://media.timeout.com/images/102496743/image.jpg"
                         class="img-fluid" alt="#" style="border-radius: 0%">
                </div>
                <div class="mt-3 mb-5 text-center">
                    <btn class="btn btn-primary btn-lg" id="edit_img">Add photo</btn>
                    <div style="visibility: hidden;">{{ form.photo }}</div>
                </div>

                {{ form.name.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.name }}
                    <span class="focus-input100"></span>
                    {{ form.name.errors }}
                </div>

                {{ form.address.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.address }}
                    <span class="focus-input100"></span>
                    {{ form.address.errors }}
                </div>

                {{ form.city.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.city }}
                    <span class="focus-input100"></span>
                    {{ form.city.errors }}
                </div>

                {{ form.zip_code.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.zip_code }}
                    <span class="focus-input100"></span>
                    {{ form.zip_code.errors }}
                </div>


                {{ form.country.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.country }}
                    <span class="focus-input100"></span>
                    {{ form.country.errors }}
                </div>

                {{ form.phone_number.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.phone_number }}
                    <span class="focus-input100"></span>
                    {{ form.phone_number.errors }}
                </div>


                {{ form.latitude.label_tag }}
                <div class="wrap-input100 mb-4">
                    {{ form.latitude }}
                    <span class="focus-input100"></span>
                    {{ form.latitude.errors }}
                </div>

                {{ form.longitude.label_tag }}
                <div class="wrap-input100 mb-4">
                    {{ form.longitude }}
                    <span class="focus-input100"></span>
                    {{ form.longitude.errors }}
                </div>

                <div class="container-login100-form-btn mt-5">
                    <button type="submit" class="login100-form-btn">Register Restaurant</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

{% block script %}
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#photo').attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#id_photo").change(function () {
            readURL(this);
        });

        $('#edit_img').click(function () {
            $("#id_photo").trigger("click");
        });
    </script>
{% endblock script %}

app/templates/client_profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Client {% endblock %}

{% block content %}
    <div class="container-login100 mt-5">
        <div class="wrap-login100 wea pt-5 pb-5">

            <form id="login-form" class="login100-form validate-form flex-sb flex-w" method="post"
                  enctype="multipart/form-data">

                <span class="login100-form-title pb-5">Client</span>

                {% if messages %}
                    <div class="body col-12 mb-4">
                        <ul>
                            {% for m in messages %}
                                <li {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                                    class="alert alert-danger"
                                {% else %}
                                    class="alert alert-success"
                                {% endif %}
                                >
                                    {{ m }}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-12 col-lg-3" style="text-align: center">
                        <div class="follow-img" style="text-align: left">
                            <img id="photo"
                                 src="{{ form.photo.initial }}"
                                 class="img-fluid" alt="#">
                        </div>
                        {% if editable %}
                            <div class="mt-3 mb-5">
                                <btn class="btn btn-primary btn-lg" id="edit_img">Add foto</btn>
                                <div style="visibility: hidden;">{{ form.photo }}</div>
                            </div>
                        {% endif %}
                    </div>
                    {% if editable %}
                        <div class="col-12 col-lg-9" style="text-align: right">
                            <btn class="btn btn-danger btn-lg" data-toggle="modal"
                                 data-target="#deleteModal"
                                 onclick="loadInfo('{{ form.email.value }}', '{{ form.first_name.value }}', '{{ form.last_name.value }}')">
                                Delete Account
                            </btn>
                        </div>
                    {% endif %}
                </div>


                {{ form.email.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.email }}
                    <span class="focus-input100"></span>
                    {{ form.email.errors }}
                </div>

                {% if editable %}
                    {{ form.new_password.label_tag }}
                    <div class="wrap-input100 mb-5">
                        {{ form.new_password }}
                        <span class="focus-input100"></span>
                        {{ form.new_password.errors }}
                    </div>

                    {{ form.repeat_password.label_tag }}
                    <div class="wrap-input100 mb-5">
                        {{ form.repeat_password }}
                        <span class="focus-input100"></span>
                        {{ form.repeat_password.errors }}
                    </div>
                {% endif %}

                {{ form.first_name.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.first_name }}
                    <span class="focus-input100"></span>
                    {{ form.first_name.errors }}
                </div>


                {{ form.last_name.label_tag }}
                <div class="wrap-input100 mb-5">
                    {{ form.last_name }}
                    <span class="focus-input100"></span>
                    {{ form.last_name.errors }}
                </div>


                {{ form.phone_number.label_tag }}
                <div class="wrap-input100 mb-4">
                    {{ form.phone_number }}
                    <span class="focus-input100"></span>
                    {{ form.phone_number.errors }}
                </div>

                {% if editable %}
                    <div class="container-login100-form-btn mt-5">
                        <button type="submit" class="login100-form-btn">Update</button>
                    </div>
                {% endif %}
            </form>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Tens a certeza que queres eliminar: </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                    {% csrf_token %}
                    <div class="modal-body">

                        {{ form.email.label_tag }}
                        <div class="wrap-input100 mb-5">
                            {{ form.email }}
                            <span class="focus-input100"></span>
                        </div>

                        {{ form.first_name.label_tag }}
                        <div class="wrap-input100 mb-5">
                            {{ form.first_name }}
                            <span class="focus-input100"></span>
                        </div>

                        {{ form.last_name.label_tag }}
                        <div class="wrap-input100 mb-5">
                            {{ form.last_name }}
                            <span class="focus-input100"></span>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button name="remove" type="submit" class="btn btn-danger">Delete Account</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block script %}
    <script>
        function loadInfo(email, first_name, last_name) {
            document.getElementById("id_first_name").value = first_name;
            document.getElementById("id_last_name").value = last_name;
            document.getElementById("id_email").value = email;
        }

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#photo').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#id_photo").change(function () {
            readURL(this);
        });

        $('#edit_img').click(function () {
            $("#id_photo").trigger("click");
        });


    </script>
{% endblock script %}